partially ported pt methods and classes of vit mae to tensorflow.
ariG23498/transformers pull request #1
Opened 2022-03-06 12:07 UTC by sayakpaul

2022-03-07 16:48 UTC, ariG23498 requested changes
Kudos for the positional embedding code. Loved it!

Minor changes that need to be done in order for us to move ahead. I think we are heading in the right direction.

2022-03-07 16:48 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        (`torch.FloatTensor` of shape (grid_size*grid_size, embed_dim) or (1+grid_size*grid_size, embed_dim): the
```suggestion
        (`tf.Tensor` of shape (grid_size*grid_size, embed_dim) or (1+grid_size*grid_size, embed_dim): the
```

2022-03-07 16:48 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +    grid_w = tf.range(grid_size, dtype=np.float32)
```suggestion
    grid_w = tf.range(grid_size, dtype=tf.float32)
```

2022-03-07 16:48 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +    emb_w = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[1])  # (H*W, D/2)
```suggestion
    emb_h = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[0])  # (W*H, D/2)
    emb_w = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[1])  # (W*H, D/2)
```

2022-03-07 16:48 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +    emb = tf.concat([emb_h, emb_w], axis=1)  # (H*W, D)
```suggestion
    emb = tf.concat([emb_h, emb_w], axis=1)  # (W*H, D)
```

2022-03-07 16:48 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +    embed_dim: output dimension for each position pos: a list of positions to be encoded: size (M,) out: (M, D)
```suggestion
    embed_dim: output dimension for each position
    pos: a list of positions to be encoded: size (M,) out: (M, D)
```

2022-03-07 16:48 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        )[None, ...]
```suggestion
        )[tf.newaxis, ...]
```

IMO this is more readable than None. WDYT?

2022-03-07 16:48 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +            sequence (`torch.LongTensor` of shape `(batch_size, sequence_length, dim)`)
```suggestion
            sequence (`tf.Tensor` of shape `(batch_size, sequence_length, dim)`)
```

2022-03-07 16:48 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +            indices=tf.repeat(ids_keep[..., None], [1, 1, dim]),
```suggestion
            indices=tf.repeat(ids_keep[..., tf.newaxis], [1, 1, dim]),
```

2022-03-08 04:54 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +    emb_w = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[1])  # (H*W, D/2)
Not sure about this.

2022-03-08 04:54 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +    emb = tf.concat([emb_h, emb_w], axis=1)  # (H*W, D)
Not sure about this.

2022-03-08 04:56 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        )[None, ...]
Conflicted between `tf.expand_dims()` then.

2022-03-08 04:57 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +            indices=tf.repeat(ids_keep[..., None], [1, 1, dim]),
Same.

2022-03-08 04:58 UTC, sayakpaul commented
@ariG23498 made the changes.

2022-03-08 05:12 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +    emb_w = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[1])  # (H*W, D/2)
If we take this [code line](https://github.com/ariG23498/transformers/blob/8d27eb36c120b032db80011c6179d462a38d30c5/src/transformers/models/vit_mae/modeling_tf_vit_mae.py#L75) under consideration, the `emb_h` and `emb_w` are width first.

2022-03-08 05:12 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +    emb = tf.concat([emb_h, emb_w], axis=1)  # (H*W, D)
Same as above!

2022-03-08 05:14 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        )[None, ...]
`[tf.newaxis, ...]` is the closest to `[None, ...]`

If we want to have a more spelt out API for this change I would always like `tf.expand_dims()`

2022-03-08 05:18 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        )[None, ...]
That in retrospect would further complicate the readability. One can add a separate line to have the dimensions expanded but that's unnecessary here because that's not gonna be reused.

2022-03-08 05:20 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +    emb_w = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[1])  # (H*W, D/2)
https://github.com/ariG23498/transformers/blob/8d27eb36c120b032db80011c6179d462a38d30c5/src/transformers/models/vit_mae/modeling_tf_vit_mae.py#L78

2022-03-08 16:03 UTC, ariG23498 requested changes

2022-03-08 16:42 UTC, sayakpaul commented
Some of the redundant stuff has been kept there on purpose. These mainly have two flavors:

* In large codebases like this, it helps to have uniform modules that have already been tested and therefore is more likely to not break. This often includes simple things too. 
* Some of the tensor shapes have been unpacked but there were never used. I think they are there for reference. Technically, this could have been added as a comment too. But I am just trying to convey some of the hard compromises you may have to make in order to impose maintainability, sanity, etc.

2022-03-08 16:44 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        batch_size, seq_length, dim = sequence.shape
Advantage?

2022-03-09 03:52 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        num_patches = (width // self.patch_size[1]) * (height // self.patch_size[0])
Taken from TFViT.

2022-03-09 03:54 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        input_tensor: tf.Tensor,
Yeah, taken from TFViT.

2022-03-09 03:56 UTC, sayakpaul commented
@ariG23498 made the further changes.

2022-03-09 04:55 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        num_patches = (width // self.patch_size[1]) * (height // self.patch_size[0])
interesting -- do you think we should raise this concern in the vit model?

2022-03-09 04:56 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        batch_size, seq_length, dim = sequence.shape
parity in the API -- the `shape_list` is build explicilty for this operation, it is better if we use it in all the palces.

WDYT?

2022-03-09 04:56 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        input_tensor: tf.Tensor,
but this makes no sense -- I strongly believe us raising this concern

2022-03-09 04:57 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        batch_size, seq_length, dim = sequence.shape
If that was the case, it would have been used in the rest of the TF models, Isn't it? Or have I missed it?

2022-03-09 04:57 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        input_tensor: tf.Tensor,
Go ahead.

2022-03-09 04:58 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        num_patches = (width // self.patch_size[1]) * (height // self.patch_size[0])
Go ahead.

2022-03-09 05:01 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        batch_size, seq_length, dim = sequence.shape
https://github.com/ariG23498/transformers/blob/915b68287c1a2210aefbcae398f92c139e9a1a4f/src/transformers/models/vit_mae/modeling_tf_vit_mae.py#L408

MY idea about the api comes from this line.

2022-03-09 05:06 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        batch_size, seq_length, dim = sequence.shape
Fair point. But this nowhere maintained i.e., you will see a mix of both `shape_list()` and `.shape`. I will freeze the developments from my end after a while temporarily. I will let you take care of this.

2022-03-09 10:02 UTC, ariG23498 commented
Hey @sayakpaul do you think we should be changing the pytorch code in the style? My intuition is to not touch it at all.

2022-03-09 10:04 UTC, sayakpaul commented
It was a mistake on my end. I will fix it.

2022-03-09 10:09 UTC, sayakpaul commented
Done @ariG23498

2022-03-09 10:37 UTC, ariG23498 commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        )  # unshuffle
Should we also try porting this code snippet with the `batch_dims=1`?

2022-03-09 10:45 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        )  # unshuffle
I will test and apply wherever necessary. Hence I mentioned "partially" in the commit message.

2022-03-10 02:54 UTC, sayakpaul commented
@ariG23498 with the latest commit (https://github.com/ariG23498/transformers/pull/1/commits/0d993edf1ad5216ec190a614201106801e7d2e16) we should be able to initialize the mode successfully. But the naming needs to be fixed so that cross-loading is successful.

2022-03-10 04:57 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        )
These should not be formatted as new lines.

2022-03-10 04:58 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +            name="dropout")
Same and elsewhere where applicable.

2022-03-10 04:58 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +            TFViTMAELayer(decoder_config, name=f"decoder_layers.{j}") for j in range(config.decoder_num_hidden_layers)
Nice work!

2022-03-10 04:59 UTC, sayakpaul commented on src/transformers/models/vit_mae/modeling_tf_vit_mae.py
> +        )
Maybe run `make style` once?

2022-03-10 05:37 UTC, ariG23498 commented
@sayakpaul I did not use the formatting yet. Right at the end -- will use the formatter and properly define black styles everywhere -- is it okay with you?

2022-03-10 05:40 UTC, sayakpaul commented
Before committing, I find it a good practice to just do `make style` and add the relevant file(s) after that and proceed to commit it. It removes unnecessary file changes from the PR.

2022-03-11 18:38 UTC, merged